# Generated by Django 4.0 on 2024-08-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_myauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
