# Generated by Django 5.0.6 on 2024-07-12 17:56

import shopapp.for_validate.for_validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, validators=[shopapp.for_validate.for_validate.validate_text]),
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.CharField(blank=True, max_length=20, validators=[shopapp.for_validate.for_validate.validate_text]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, validators=[shopapp.for_validate.for_validate.validate_text]),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(default=0, validators=[shopapp.for_validate.for_validate.validate_0_100]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[shopapp.for_validate.for_validate.validate_text]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[shopapp.for_validate.for_validate.validate_positive]),
        ),
    ]

