# Generated by Django 5.0.6 on 2024-07-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_order_delivery_address_alter_order_promocode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]

