# Generated by Django 5.0.6 on 2024-07-12 17:56

import requestdataapp.for_validate.for_validate
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.BigIntegerField(validators=[requestdataapp.for_validate.for_validate.validate_file_size])),
            ],
        ),
    ]
