# Generated by Django 5.0.6 on 2024-07-12 18:25

import requestdataapp.for_validate.for_validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestdataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=20, validators=[requestdataapp.for_validate.for_validate.validate_ip])),
                ('time_run', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['user_ip'],
            },
        ),
    ]
